### ISSUE TITLE
Fix test_initialize_redefine

### ISSUE THREAD

**Issue by saturnflyer** [saturnflyer/polyfill-data#1]
The rules around redefining the initialize method are not covering all test cases.

```shell
> bundle exec rake
Run options: --seed 31975

# Running:

.........E

Finished in 0.000614s, 16286.6445 runs/s, 83061.8867 assertions/s.

  1) Error:
TestData#test_initialize_redefine:
ArgumentError: ArgumentError
    /Users/jim/Projects/polyfill-data/lib/data.rb:23:in `block in define'
    /Users/jim/Projects/polyfill-data/test/test_data.rb:96:in `test_initialize_redefine'

10 runs, 51 assertions, 0 failures, 1 errors, 0 skips
```

**Comment by saturnflyer** [comment]
https://github.com/saturnflyer/polyfill-data/commit/808d99ad09f515379ea4275bf956d675dab17cb9
